# ~/.tmux.conf - 使用模块化脚本的配置

# =============================================================================
# 基础设置
# =============================================================================
set -g default-terminal "screen-256color"
#set -g default-terminal "alacritty"
#set -g default-terminal "kitty"

#set-option -g default-command $SHELL
if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'

set -g prefix ^a
unbind ^b
bind a send-prefix

set -g @ifname "wlp3s0"
set -g @weather_location "深圳"

# 单行状态栏
set -g status on
# 两行状态栏, 全局窗口statusline
#set -g status 2

source ~/.tmux/options.tmux
source ~/.tmux/bindings.tmux
source ~/.tmux/statusline.tmux
source ~/.tmux/plugings.tmux
